<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Lawyers;
use App\Models\ServiceDetails;

class LawyerSchedule extends Model
{
    /**
     * @var string
     */
    protected $table = "lawyers_schedule";

    /**
     * @var string[]
     */
    protected $hidden = ['lawyers_id'];

    /**
     * @var array
     */
    protected $guarded = [];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function lawyers()
    {
        return $this->belongsTo(Lawyers::class); // TODO: Change the autogenerated stub
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function service_details()
    {
        return $this->belongsTo(ServiceDetails::class);
    }
}
